// Generated by CoffeeScript 1.4.0
(function() {
  var app, config, default_config, developer_config, development_config, express, http, mongoose, path, production_config, routes, _;

  _ = require('underscore');

  express = require("express");

  mongoose = require("mongoose");

  routes = require("./routes");

  http = require("http");

  path = require("path");

  default_config = require('config').Default;

  production_config = require('config').Production;

  config = _.defaults(production_config, default_config);

  if (process.env.NODE_ENV = 'development') {
    development_config = require('config').Development || {};
    developer_config = require('config')[process.env.NODE_DEVELOPER] || {};
    config = _.defaults(development_config, config);
    config = _.defaults(developer_config, config);
  }

  app = express();

  app.configure(function() {
    app.set("port", config.port);
    app.set("views", __dirname + "/views");
    app.set("view engine", "jade");
    app.use(express.favicon());
    app.use(express.logger("dev"));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    return app.use(express["static"](path.join(__dirname, "public")));
  });

  app.configure("development", function() {
    return app.use(express.errorHandler());
  });

  routes.init(app);

  mongoose.connect(config.dbHost, config.dbName, config.dbPort);

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);
