// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";

  var common, user;

  common = require("./common");

  user = require("./user");

  exports.init = function(app) {
    app.get("/", common.index);
    return app.get("/users", user.list);
  };

}).call(this);
