// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";

  var builder, card, cards, common;

  //common = require("./common");
  //cards = require("./cards");
  ///card = require("./card");
  builder = require("./builder");

  var Api =  require("../api").Api;
  var api = new Api();

  exports.init = function(app) {
    app.all('/api/*', function(req, res){
      api.init(req, res);
    });

    app.get("/builder", builder.index);

    app.get("/test", function(req, res){
      res.render('test', {
        title: 'jQuery Sandbox'
      });
    });
    /*
    app.get("/", common.index);
    app.get("/card/id/:id", card.get);
    app.get("/cards", cards.list);
    app.get("/cards/start/:start/limit/:limit", cards.list);
    return app.get("/builder", builder.index);
    */
  };

}).call(this);
