// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";

  var card, cards, common;

  common = require("./common");

  cards = require("./cards");

  card = require("./card");

  exports.init = function(app) {
    app.get("/", common.index);
    app.get("/card/id/:id", card.get);
    return app.get("/cards", cards.list);
  };

}).call(this);
