// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";

  var Card;

  Card = require("../models/card.js");

  exports.list = function(req, res) {
    new Card({
      title: "test-title",
      description: "test-desc"
    }).save();
    return Card.find(function(err, cards) {
      return res.send(cards);
    });
  };

}).call(this);
